### ISSUE TITLE
React to the recent breaking changes in the hosting stack

### ISSUE THREAD

**Issue by kevinchalet** [aspnet-contrib/AspNet.Hosting.Extensions#10]
@MartinJohns PTAL when you have a minute: https://github.com/aspnet/Hosting/commit/8f5f8d28d00468725d9fd8dd95123f43d22f2c3c.

FYI, this change has not been included in ASP.NET Core RC2 so it only impacts our `dev` branch:
https://ci.appveyor.com/project/aspnet-contrib/aspnet-hosting-extensions/branch/dev

**Comment by MartinJohns** [comment]
I'll take a look this weekend. :+1:
