### ISSUE TITLE
Adapt other katana keys

### ISSUE THREAD

**Issue by davidfowl** [aspnet-contrib/AspNet.Hosting.Extensions#2]
Like the stuff in here:

https://github.com/SignalR/SignalR/blob/3a219c101587333d562f04f30903d50ad9773e1c/src/Microsoft.AspNet.SignalR.Core/Owin/Infrastructure/OwinEnvironmentExtensions.cs

and 

http://katanaproject.codeplex.com/SourceControl/latest#src/Microsoft.Owin.Security/DataProtection/AppBuilderExtensions.cs

**Comment by kevinchalet** [comment]
Good idea :+1:

Wanna submit a PR? :smile:

**Comment by davidfowl** [comment]
Not really :smile:
