### ISSUE TITLE
Using OWIN authentication middleware in .NET Core

### ISSUE THREAD

**Issue by mshindal** [aspnet-contrib/AspNet.Hosting.Extensions#21]
I'm currently using this library to add some OWIN authentication middleware to a .NET Core application. I've used the `UseKatana()` method of this library to add the middleware, but the `[Authorize]` attribute appears to not work. The attribute is ignored and the page is shown whether the user is logged in or not.

Do you know of any way to get this to work?

**Comment by kevinchalet** [comment]
> Do you know of any way to get this to work?

Nope. The Katana and ASP.NET Core authentication stacks are so different that it's _practically_ impossible to make them interoperate. If you have OWIN/Katana components that need authentication, I suggest using security middleware design for OWIN/Katana.
